insert into user_sa (name ,email,last_upd_ts,last_upd_usr_id,crt_dt ,crt_usr_id ) values ('SandeepBhupathi','sandeepbupathi08@gmail.com',current_timestamp,'SYSTEM',current_date,'SYSTEM');
insert into user_sa (name ,email,last_upd_ts,last_upd_usr_id,crt_dt ,crt_usr_id ) values ('Sandeep1','sandeepbupathi07@gmail.com',current_timestamp,'SYSTEM',current_date,'SYSTEM');
insert into user_sa (name ,email,last_upd_ts,last_upd_usr_id,crt_dt ,crt_usr_id )  values ('Sandeep3','sandeepbupathi09@gmail.com',current_timestamp,'SYSTEM',current_date,'SYSTEM');
insert into user_sa  (name ,email,last_upd_ts,last_upd_usr_id,crt_dt ,crt_usr_id ) values ('Sowmya','sandeepbupathi10@gmail.com',current_timestamp,'SYSTEM',current_date,'SYSTEM');
insert into address_sa values (1,30080,1);
insert into address_sa values (2,30081,2);
insert into address_sa values (3,30082,3);
insert into address_sa values (4,30084,2);
insert into address_sa values (5,30085,1);
insert into address_stat_cd values (1,'COM');
insert into address_stat_cd values (2,'RUR');
insert into address_stat_cd values (3,'CONT');